worktimer/models.py
from worktimer import db
from datetime import datetime, date

class WorkTime(db.Model):
  id = db.Column(db.Integer, primary_key=True,autoincrement=True)
  work_time = db.Column(db.DateTime(),nullable=False)
  created_date = db.Column(db.Date(), default=datetime.utcnow,nullable=False)

worktimer/summary/forms.py
from flask_wtf import FlaskForm
from wtforms.fields.core import DecimalField
from wtforms.fields.html5 import DateField
from wtforms.fields.simple import SubmitField

class DateForm(FlaskForm):
  date = DateField('Choose a date')
  submitDate = SubmitField('Submit')

class converterForm(FlaskForm):
  time = DecimalField('Enter a time in hours to convert to H:M:S')
  submitTime = SubmitField('Submit')

worktimer/__init__.py
from flask import Flask
from worktimer.config import Config
from flask_sqlalchemy import SQLAlchemy

db =SQLAlchemy()

def create_app(config_class = Config):
  app = Flask(__name__)
  app.config.from_object(Config)

  db.init_app(app)

  from worktimer.stopwatch.routes import sw
  from worktimer.summary.routes import details
  app.register_blueprint(sw)
  app.register_blueprint(details)

  return app

worktimer/stopwatch/routes.py
from datetime import datetime, date
from worktimer.models import WorkTime,db
from flask import Blueprint, render_template,redirect,request


sw = Blueprint('sw', __name__)


@sw.route('/stopwatch')
@sw.route('/')
def stopwatch():
  return render_template('stopwatch.html')

@sw.route('/saveTime', methods=['POST','GET'])
def saveTime():
  if request.method == 'POST':
    timeWorked = request.get_json()
    time_obj = datetime.strptime(timeWorked['workTime'],'%H:%M:%S')
    print(time_obj)
    #save to database
    worktime = WorkTime(work_time=time_obj,created_date=date.today())
    db.session.add(worktime)
    db.session.commit()
    return "success"
  return "error"

worktimer/summary/routes.py
from flask import Blueprint, render_template, request
from datetime import date
import json
from worktimer.summary.utils import (getWeekDates, getTimesFromDb,
                                     avgWorkTime, getTimeCurrentDate)
from worktimer.summary.forms import DateForm, converterForm


details = Blueprint('details', __name__)

@details.route('/summary', methods=["POST", "GET"])
def summary():
    formDate = DateForm()
    formConverter = converterForm()
    
    if formDate.validate_on_submit():
        inputDate = formDate.date.data
        if inputDate == "":
            #get current date
            weekDates = getWeekDates(date.today())
            data = getTimesFromDb(weekDates)
        else:
            weekDates = getWeekDates(inputDate)
            data = getTimesFromDb(weekDates)
    else:
        weekDates = getWeekDates(date.today())
        data = getTimesFromDb(weekDates)

    avgTime = avgWorkTime()

    
    
    return render_template('summary.html', data=data, startDate=weekDates[0], endDate=weekDates[len(weekDates)-1], avgTime=avgTime,formDate=formDate,formConverter=formConverter)




@details.route('/convertTime', methods=['POST','GET'])
def convertTime():
  if request.method == 'POST':
    inputTimeArr = request.get_json()
    if inputTimeArr['timeInput'] != "":
        inputTime = float(inputTimeArr['timeInput'])

        #https://www.calculatorsoup.com/calculators/time/decimal-to-time-calculator.php
        #Click on link for logic below
        hour = inputTime
        fullHour = int(hour)
        decimalHour = hour - fullHour
        min = decimalHour * 60
        fullMin = int(min)
        decimalMin = min - fullMin
        fullSec = round(decimalMin *60,0)
        fullSec = int(fullSec)

        #If seconds/minutes/hours are only one digit, add a leading 0 to the value
        if fullSec < 10:
            displaySeconds = "0" + str(fullSec)
        else:
            displaySeconds = str(fullSec)
        
        if fullMin < 10:
            displayMinutes = "0" + str(fullMin)
        else:
            displayMinutes = str(fullMin)

        if fullHour < 10:
            displayHours = "0" + str(fullHour)
        else:
            displayHours = str(fullHour)
    
        
        displayTime = displayHours +":" + displayMinutes +":" + displaySeconds 
        print(displayTime)
        return json.dumps(displayTime)
  return json.dumps("00:00:00")

worktimer/templates/header.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='CSS/bootstrap.css') }}">
  <!--Bootstrap-->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" cross-origin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>

  <!--jQuery-->
  <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
  
  <!--chart.js-->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js" integrity="sha512-d9xgZrVZpmmQlfonhQUvTR7lMPtO7NkZMkA0ABN3PHCbKA5nqylQ/yWlFAyY6hYgdF1Qh6nYiuADWwKB4C2WSw==" crossorigin="anonymous"></script>

  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='CSS/custom.css') }}">
  <script src="{{url_for('static', filename='stopWatch.js')}}"></script>

  <title>Work Timer</title>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="{{ url_for('details.summary')}}">Work Timer</a>
    <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarColor01"
      aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="navbar-collapse collapse" id="navbarColor01">
      <ul class="navbar-nav mr-auto">
        <li "{% if active_page=='stopwatch' %} class=" nav-item active" {% endif %}">
          <a class="nav-link" href="{{ url_for('sw.stopwatch')}}">Stopwatch</a>
        </li>
        <li "{% if active_page=='summary' %} class=" nav-item active" {% endif %}">
          <a class="nav-link" href="{{ url_for('details.summary')}}">Summary</a>
        </li>
      </ul>
    </div>
  </nav>
  {% block content %}

  {% endblock content %}




</body>

</html>

worktimer/templates/stopwatch.html
{% set active_page = "stopwatch" %}

{% extends 'header.html' %}

{% block content %}
<div class="container">
  <div id="display">
    00:00:00
  </div>

  <div class="buttons">
    <button type="button" class="btn btn-primary" id="startPause" onclick="startPause()">Start</button>
    <button type="button" class="btn btn-secondary" id="reset" onclick="reset()">Reset</button>
  </div>

  <div class="saveDiv">
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="timeWorkedModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title center">Amount of Time Worked</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>


{% endblock content %}

worktimer/templates/summary.html
{% set active_page = "summary" %}

{% extends 'header.html' %}

{% block content %}
<br />
<div class="workContainer">
        <label for="avgWork">Average Work Time per day (Hrs):</label>
        <input type="text" readonly="readonly" class="form-control-plaintext" id="workTime" name="avgWork"
                value="{{ avgTime }}">
</div>
<br />
<br />
<div class="canvasContainer">
        <canvas id="myChart" width="200" height="500"></canvas>
</div>
<br />
<br />

<!--
<div class="dateInput">
        <form method="POST" action="">
                <label for="chooseDate">Choose a date to the week's time worked:</label>
                <input name="chooseDate" type="date">
                <button type="submit" class="btn btn-primary">Submit</button>
        </form>
</div>
-->
<div class="dateInput">
        <form method="POST" action="">
                {{ formDate.hidden_tag() }}
                <fieldset>
                        <legend><b>Choose a date to display summary</b></legend>
                        <div class="form-group">
                                {{ formDate.date.label}}
                                {{ formDate.date(class = "") }}
                        </div>
                        {{ formDate.submitDate(class = "btn btn-primary") }}
                </fieldset>
        </form>
</div>
<br />
<div class="dateInput">
        <form method="POST" action="" id = "formTime">
                <fieldset>
                        <legend><b>Enter a time to convert to HH:MM:SS</b></legend>
                        <div class="form-group">
                                <label for="timeInput">Choose a date to the week's time worked:</label>
                                <input type = "text" name="timeInput" class = "form-control w-50 offset-3" id = "timeInput">
                                <br/>
                                <input class="form-control w-50 offset-3" type="text" placeholder="00:00:00" id = "outputTime" readonly>
                        </div>
                        <button type="submit" class="btn btn-primary" id = "submitTime">Convert</button>
                </fieldset>
        </form>
</div>


<script>
        var ctx = document.getElementById('myChart');
        var myChart = new Chart(ctx, {
                type: 'horizontalBar',
                data: {
                        labels: ['Mon', 'Tue', 'Wed', 'Thurs', 'Fri', 'Sat', 'Sun'],
                        datasets: [{
                                label: 'Time Worked (Hrs)',
                                data: {{ data| tojson }},
                backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)',
                'rgba(255, 194, 144, 0.2)'
        ],
                borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)',
                'rgba(255, 194, 144, 1)'
        ],
                borderWidth: 1
                        }]
                },
        options: {
                responsive: true,
                        maintainAspectRatio: false,
                                title: {
                        display: true,
                                text: '{{ startDate }} to {{ endDate }}'
                },
                scales: {
                        yAxes: [{
                                ticks: {
                                        beginAtZero: true
                                }
                        }]
                }
        }
        });
</script>
{% endblock content %}